form/config/routes.rb
Bookstore::Application.routes.draw do
  resources :authors
  resources :books
  root to: 'books#index'
end

form/app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name
  has_many :authorships
  has_many :books, through: :authorships
  
  def self.tokens(query)
    authors = where("name like ?", "%#{query}%")
    if authors.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      authors
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

form/app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

form/app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name, :author_tokens
  has_many :authorships
  has_many :authors, through: :authorships
  attr_reader :author_tokens
  
  def author_tokens=(tokens)
    self.author_ids = Author.ids_from_tokens(tokens)
  end
end

form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

form/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.order(:name)
    respond_to do |format|
      format.html
      format.json { render json: @authors.tokens(params[:q]) }
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params[:author])
    if @author.save
      redirect_to @author, notice: "Successfully created author."
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      redirect_to @author, notice: "Successfully updated author."
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_url, notice: "Successfully destroyed author."
  end
end

form/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to @book, notice: "Successfully created book."
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to @book, notice: "Successfully updated book."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url, notice: "Successfully destroyed book."
  end
end

form/app/helpers/application_helper.rb
module ApplicationHelper
end

form/app/helpers/authors_helper.rb
module AuthorsHelper
end

form/app/helpers/books_helper.rb
module BooksHelper
end

form/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

form/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

form/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

form/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

form/app/views/authors/show.html.erb
<h1>Author</h1>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

form/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author_tokens, "Authors" %><br />
    <%= f.text_field :author_tokens, data: {load: @book.authors} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

form/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

form/app/views/books/index.html.erb
<h1>Books</h1>

<% if @books.empty? %>
  <strong>Currently no books.</strong>
<% else %>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= link_to "Show", book %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
      <td><%= link_to "Destroy", book, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>
<% end %>

<p><%= link_to "New Book", new_book_path %></p>

form/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

form/app/views/books/show.html.erb
<h1>Book</h1>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<strong>Authors:</strong>
<ul>
<% @book.authors.each do |author| %>
  <li><%= author.name %></li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_book_path(@book) %> |
  <%= link_to "Destroy", @book, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", books_path %>
</p>

form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>